{% set name = "mapbox-vector-tile" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9a0572e483c7b06762af73b9b5ee5f4e58441bcca9190105fe55cec71dd16cd8

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry

  run:
    - future
    - protobuf >=5.26.1,<6.0.0
    - pyclipper >=1.3.0,<2.0.0
    - python >={{ python_min }}
    - setuptools
    - shapely >=2.0.0,<3.0.0

test:
  imports:
    - mapbox_vector_tile
    - mapbox_vector_tile.Mapbox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tilezen/mapbox-vector-tile
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mapbox Vector Tile
  dev_url: https://github.com/tilezen/mapbox-vector-tile

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - benhuff
    - jan-janssen
